"""Emit the constant weight array and the C kernel that reads it.

`emit(packed, out_dir)` writes three files and nothing else:

  ss_weights.c   one `const unsigned char SS_W[]`, aligned, in its own section, holding every tensor in the order the
                 kernel walks it: trunk levels packed at the trained bit width, group scales as float16, biases and
                 LayerNorm parameters as float32, embeddings and head matrices as int8 rows with one float32 scale.
  ss_kernel.h    the shapes, the offsets into `SS_W[]`, and the two entry points.
  ss_kernel.c    a transliteration of `oracle.py`: the same algorithm, the same constants, the same order of
                 operations, so that the two agree bit for bit (gate G1a).

The kernel allocates nothing: the caller supplies a scratch buffer whose size is a compile-time constant.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

import numpy as np

from static_student.codegen import kernel_math as km
from static_student.codegen.oracle import inv_sqrt_head_dim
from static_student.codegen.pack import Packed, QuantLinear, RowLinear
from static_student.student.model import CLS, MAX_LEN, PAD, POINTERS, UNIT_CLASSES
from static_student.student.quant import GROUP

F32 = np.float32


class Blob:
    """The byte stream of `SS_W[]`, built in the kernel's reading order; every append returns its offset."""

    def __init__(self) -> None:
        self.buf = bytearray()
        self.names: list[tuple[str, int, int]] = []

    def add(self, name: str, data: bytes, align: int = 4) -> int:
        while len(self.buf) % align:
            self.buf.append(0)
        off = len(self.buf)
        self.buf += data
        self.names.append((name, off, len(data)))
        return off

    def f32(self, name: str, a: np.ndarray) -> int:
        return self.add(name, np.ascontiguousarray(a, dtype="<f4").tobytes())

    def f16(self, name: str, a: np.ndarray) -> int:
        return self.add(name, np.ascontiguousarray(a, dtype="<f2").tobytes(), align=2)

    def i8(self, name: str, a: np.ndarray) -> int:
        lo, hi = int(np.min(a)), int(np.max(a))
        if lo < -128 or hi > 127:
            raise ValueError(f"{name}: levels span [{lo}, {hi}], which does not fit one byte; the kernel reads int8 rows")
        return self.add(name, np.ascontiguousarray(a, dtype="<i1").tobytes(), align=1)

    def packed_levels(self, name: str, levels: np.ndarray, bits: int) -> int:
        """Levels at `bits` each, LSB first, one whole number of bytes per group of 32 (8, 12 or 16 bytes)."""
        out, per_group = bytearray(), GROUP * bits // 8
        assert GROUP * bits % 8 == 0
        flat = (levels.astype(np.int32) & ((1 << bits) - 1)).reshape(-1, GROUP)
        for row in flat:
            acc, nbits, chunk = 0, 0, bytearray()
            for v in row:
                acc |= int(v) << nbits
                nbits += bits
                while nbits >= 8:
                    chunk.append(acc & 0xFF)
                    acc >>= 8
                    nbits -= 8
            assert nbits == 0 and len(chunk) == per_group
            out += chunk
        return self.add(name, bytes(out), align=1)


def _c_array(data: bytes, per_line: int = 24) -> str:
    lines = [", ".join(f"0x{b:02x}" for b in data[i:i + per_line]) for i in range(0, len(data), per_line)]
    return ",\n  ".join(lines)


def build_blob(p: Packed) -> tuple[Blob, dict]:
    b, off = Blob(), {}
    off["tok_levels"], off["tok_scale"] = b.i8("tok.levels", p.tok.levels), b.f32("tok.scale", p.tok.scale)
    off["pos_levels"], off["pos_scale"] = b.i8("pos.levels", p.pos.levels), b.f32("pos.scale", p.pos.scale)
    off["ln_in_w"], off["ln_in_b"] = b.f32("ln_in.weight", p.ln_in[0]), b.f32("ln_in.bias", p.ln_in[1])
    for i, blk in enumerate(p.blocks):
        for name in ("q", "k", "v", "o", "up", "down"):
            l: QuantLinear = blk[name]
            off[f"b{i}_{name}_lv"] = b.packed_levels(f"b{i}.{name}.levels", l.levels, p.bits)
            off[f"b{i}_{name}_sc"] = b.f16(f"b{i}.{name}.scales", l.scales)
            off[f"b{i}_{name}_bi"] = b.f32(f"b{i}.{name}.bias", l.bias)
        for ln in ("ln1", "ln2"):
            off[f"b{i}_{ln}_w"] = b.f32(f"b{i}.{ln}.weight", blk[ln][0])
            off[f"b{i}_{ln}_b"] = b.f32(f"b{i}.{ln}.bias", blk[ln][1])
    for name, r in (("ptr", p.pointers), ("unit", p.unit), ("defer", p.defer)):
        off[f"{name}_levels"] = b.i8(f"{name}.levels", r.levels)
        off[f"{name}_scale"] = b.f32(f"{name}.scale", r.scale)
        off[f"{name}_bias"] = b.f32(f"{name}.bias", r.bias)
    return b, off


HEADER = """/* Generated by static_student.codegen.emit. Do not edit. */
#ifndef SS_KERNEL_H
#define SS_KERNEL_H
#include <stddef.h>
#include <stdint.h>

#define SS_LAYERS {layers}
#define SS_DMODEL {d}
#define SS_HEADS {heads}
#define SS_HEAD_DIM {head_dim}
#define SS_FFN {ffn}
#define SS_MAX_LEN {max_len}
#define SS_BITS {bits}
#define SS_GROUP {group}
#define SS_VOCAB {vocab}
#define SS_PAD {pad}
#define SS_CLS {cls}
#define SS_POINTERS {n_ptr}
#define SS_UNITS {n_unit}
#define SS_WEIGHT_BYTES {nbytes}u

extern const unsigned char SS_W[SS_WEIGHT_BYTES];

/* Scratch the kernel works in. The caller owns it; the kernel never allocates. */
typedef struct {{
  float x[SS_MAX_LEN * SS_DMODEL];
  float h[SS_MAX_LEN * SS_FFN];
  float qkv[3][SS_MAX_LEN * SS_DMODEL];
  float att[SS_MAX_LEN];
  float ctx[SS_MAX_LEN * SS_DMODEL];
  int8_t xq[SS_MAX_LEN * SS_FFN];
  float xs[SS_MAX_LEN];
  int8_t wbuf[SS_FFN * SS_DMODEL];                 /* one linear's levels, unpacked once per call */
  float gsbuf[SS_FFN * SS_DMODEL / SS_GROUP];      /* and its group scales, converted once per call */
}} ss_scratch;

typedef struct {{
  int32_t ptr[SS_POINTERS]; /* argmax position per pointer head; 0 means "field absent" */
  int32_t unit;             /* argmax unit class */
  float score;              /* the contract score: summed log-probability of the chosen positions and unit */
  float defer_logit;        /* the defer head, reported for the ablation, not used by the contract */
}} ss_result;

/* Runs the student on one payload. `len` is clamped to SS_MAX_LEN - 1. Returns 0 on success. */
int ss_forward(const uint8_t *payload, size_t len, ss_scratch *scratch, ss_result *out);

#endif
"""



KERNEL = r"""/* Generated by static_student.codegen.emit. Do not edit.
 *
 * A transliteration of static_student/codegen/oracle.py. Every reduction is a sequential loop and every transcendental
 * is computed here rather than taken from libm, because the reference must be reproducible bit for bit on any host.
 * Build with -O3 -ffp-contract=off and without -ffast-math: contraction into FMA would change the results.
 *
 * Where the target has one, the 8-bit dot product uses the hardware instruction. That is safe for the bit-exactness
 * guarantee precisely because it is integer: the products are exact and the accumulation order of an exact integer sum
 * does not matter. The floating-point reductions are deliberately left scalar and in order, because vectorizing them
 * would reassociate the sums and change the last bits.
 */
#include "ss_kernel.h"
#include <math.h>
#include <string.h>

#if defined(__ARM_NEON) && defined(__ARM_FEATURE_DOTPROD) && (SS_GROUP == 32)
#include <arm_neon.h>
#define SS_DOTPROD 1
#endif

static inline int32_t dot_group(const int8_t *a, const int8_t *b) {
#ifdef SS_DOTPROD
  int32x4_t acc = vdupq_n_s32(0);
  acc = vdotq_s32(acc, vld1q_s8(a), vld1q_s8(b));
  acc = vdotq_s32(acc, vld1q_s8(a + 16), vld1q_s8(b + 16));
  return vaddvq_s32(acc);
#else
  int32_t s = 0;
  for (int i = 0; i < SS_GROUP; i++) s += (int32_t)a[i] * (int32_t)b[i];
  return s;
#endif
}

#define W_AT(off) ((const void *)(SS_W + (off)))
static const float MAGIC = 12582912.0f;

static inline float rne(float x) { return (x + MAGIC) - MAGIC; }

static float ss_expf(float x) {
  const float LOG2E = 1.4426950408889634f, LN2_HI = 0.693145751953125f, LN2_LO = 1.428606765330187e-06f;
  if (x < -87.0f) return 0.0f;
  float k = rne(x * LOG2E);
  float r = (x - k * LN2_HI) - k * LN2_LO;
  float p = 0.0013888889f;
  p = p * r + 0.008333334f; p = p * r + 0.041666668f; p = p * r + 0.16666667f;
  p = p * r + 0.5f;         p = p * r + 1.0f;         p = p * r + 1.0f;
  int ki = (int)k; if (ki < -126) ki = -126; if (ki > 127) ki = 127;
  union { uint32_t u; float f; } two_k; two_k.u = (uint32_t)(ki + 127) << 23;
  return p * two_k.f;
}

static float ss_logf(float x) {
  const float LN2 = 0.6931471805599453f;
  union { float f; uint32_t u; } b; b.f = x;
  int e = (int)(b.u >> 23) - 127;
  union { uint32_t u; float f; } mm; mm.u = (b.u & 0x7FFFFFu) | (127u << 23);
  float m = mm.f;
  if (m > 1.4142135623730951f) { m *= 0.5f; e += 1; }
  float t = (m - 1.0f) / (m + 1.0f), t2 = t * t;
  float p = 2.0f / 11.0f;
  p = p * t2 + 2.0f / 9.0f; p = p * t2 + 2.0f / 7.0f; p = p * t2 + 2.0f / 5.0f;
  p = p * t2 + 2.0f / 3.0f; p = p * t2 + 2.0f;
  return (float)e * LN2 + t * p;
}

static float ss_erff(float x) {
  const float P = 0.3275911f;
  float s = x < 0.0f ? -1.0f : 1.0f, a = x < 0.0f ? -x : x;
  float t = 1.0f / (1.0f + P * a);
  float p = 1.061405429f;
  p = p * t + -1.453152027f; p = p * t + 1.421413741f; p = p * t + -0.284496736f; p = p * t + 0.254829592f;
  return s * (1.0f - p * t * ss_expf(-(a * a)));
}

static inline float ss_gelu(float x) { return 0.5f * x * (1.0f + ss_erff(x * 0.70710678118654752f)); }

static float half_to_float(uint16_t h) {
  uint32_t sign = (uint32_t)(h & 0x8000u) << 16, exp = (h >> 10) & 0x1Fu, man = h & 0x3FFu;
  union { uint32_t u; float f; } o;
  if (exp == 0) {
    if (man == 0) { o.u = sign; return o.f; }
    exp = 127 - 15 + 1;                       /* subnormal: normalize it */
    while (!(man & 0x400u)) { man <<= 1; exp--; }
    man &= 0x3FFu;
  } else if (exp == 31) { o.u = sign | 0x7F800000u | (man << 13); return o.f; }
  else exp = exp - 15 + 127;
  o.u = sign | (exp << 23) | (man << 13);
  return o.f;
}

/* mean and biased variance by sequential summation; 1/sqrtf is correctly rounded, so it is portable */
static void layer_norm(float *x, int n, int d, const float *w, const float *b) {
  for (int t = 0; t < n; t++) {
    float *row = x + (size_t)t * d, sum = 0.0f;
    for (int i = 0; i < d; i++) sum += row[i];
    float mean = sum / (float)d, var = 0.0f;
    for (int i = 0; i < d; i++) { float dx = row[i] - mean; var += dx * dx; }
    float inv = 1.0f / sqrtf(var / (float)d + 1e-5f);
    for (int i = 0; i < d; i++) row[i] = (row[i] - mean) * inv * w[i] + b[i];
  }
}

/* one int8 scale per token (ADR-0009), so a token's result never depends on what follows it */
static void quantize_rows(const float *x, int n, int d, int8_t *q, float *scale) {
  for (int t = 0; t < n; t++) {
    const float *row = x + (size_t)t * d;
    float amax = 0.0f;
    for (int i = 0; i < d; i++) { float a = row[i] < 0.0f ? -row[i] : row[i]; if (a > amax) amax = a; }
    float s = (amax < 1e-8f ? 1e-8f : amax) / 127.0f;
    scale[t] = s;
    for (int i = 0; i < d; i++) {
      float v = rne(row[i] / s);
      q[(size_t)t * d + i] = (int8_t)(v < -127.0f ? -127.0f : (v > 127.0f ? 127.0f : v));
    }
  }
}

/* y[t, o] = scale[t] * sum_g group_scale[o, g] * <levels[o, g], xq[t, g]> + bias[o]
 *
 * The packed levels are unpacked once per call rather than once per token, so the per-token loop reads both operands
 * contiguously; the accumulation over groups stays in ascending order, which is what keeps the result bit-identical
 * to the reference. */
static void linear(const int8_t *xq, const float *scale, int n, int in, int out,
                   const unsigned char *levels, const uint16_t *gscale, const float *bias, float *y,
                   int8_t *wbuf, float *gsbuf) {
  const int groups = in / SS_GROUP, gbytes = SS_GROUP * SS_BITS / 8;
  for (int o = 0; o < out; o++) {
    for (int g = 0; g < groups; g++) {
      const unsigned char *src = levels + ((size_t)o * groups + g) * gbytes;
      int8_t *dst = wbuf + (size_t)o * in + (size_t)g * SS_GROUP;
      uint32_t acc = 0;
      int nbits = 0, bi = 0;
      for (int i = 0; i < SS_GROUP; i++) {        /* SS_BITS-wide two's complement, least significant first */
        while (nbits < SS_BITS) { acc |= (uint32_t)src[bi++] << nbits; nbits += 8; }
        int v = (int)(acc & ((1u << SS_BITS) - 1u));
        acc >>= SS_BITS; nbits -= SS_BITS;
        dst[i] = (int8_t)(v >= (1 << (SS_BITS - 1)) ? v - (1 << SS_BITS) : v);
      }
      gsbuf[(size_t)o * groups + g] = half_to_float(gscale[(size_t)o * groups + g]);
    }
  }
  for (int t = 0; t < n; t++) {
    const int8_t *xr = xq + (size_t)t * in;
    const float st = scale[t];
    for (int o = 0; o < out; o++) {
      const int8_t *w = wbuf + (size_t)o * in;
      const float *gs = gsbuf + (size_t)o * groups;
      float acc = 0.0f;
      for (int g = 0; g < groups; g++) acc += (float)dot_group(w + (size_t)g * SS_GROUP, xr + (size_t)g * SS_GROUP) * gs[g];
      y[(size_t)t * out + o] = acc * st + bias[o];
    }
  }
}

/* head matrices ship as int8 rows with one scale each; they are dequantized and applied in float, as in the reference */
static void row_linear(const float *x, int d, int out, const int8_t *levels, const float *scale, const float *bias, float *y) {
  for (int o = 0; o < out; o++) {
    float acc = 0.0f, s = scale[o];
    for (int i = 0; i < d; i++) acc += x[i] * ((float)levels[(size_t)o * d + i] * s);
    y[o] = bias ? acc + bias[o] : acc;
  }
}

int ss_forward(const uint8_t *payload, size_t len, ss_scratch *S, ss_result *out) {
  if (!payload || !S || !out) return -1;
  if (len > (size_t)(SS_MAX_LEN - 1)) len = SS_MAX_LEN - 1;
  const int n = (int)len + 1, d = SS_DMODEL;

  int ids[SS_MAX_LEN];
  ids[0] = SS_CLS;
  for (size_t i = 0; i < len; i++) ids[i + 1] = (int)payload[i];

  const int8_t *tok_lv = (const int8_t *)W_AT(SS_OFF_TOK_LEVELS), *pos_lv = (const int8_t *)W_AT(SS_OFF_POS_LEVELS);
  const float *tok_sc = (const float *)W_AT(SS_OFF_TOK_SCALE), *pos_sc = (const float *)W_AT(SS_OFF_POS_SCALE);
  for (int t = 0; t < n; t++)
    for (int i = 0; i < d; i++)
      S->x[(size_t)t * d + i] = (float)tok_lv[(size_t)ids[t] * d + i] * tok_sc[ids[t]]
                              + (float)pos_lv[(size_t)t * d + i] * pos_sc[t];
  layer_norm(S->x, n, d, (const float *)W_AT(SS_OFF_LN_IN_W), (const float *)W_AT(SS_OFF_LN_IN_B));

  for (int l = 0; l < SS_LAYERS; l++) {
    const struct ss_layer *L = &SS_LAYER[l];
    quantize_rows(S->x, n, d, S->xq, S->xs);
    for (int p = 0; p < 3; p++)
      linear(S->xq, S->xs, n, d, d, SS_W + L->qkv_lv[p], (const uint16_t *)W_AT(L->qkv_sc[p]),
             (const float *)W_AT(L->qkv_bi[p]), S->qkv[p], S->wbuf, S->gsbuf);
    const float inv_sqrt = SS_INV_SQRT_HEAD_DIM;
    for (int h = 0; h < SS_HEADS; h++) {
      const int base = h * SS_HEAD_DIM;
      for (int i = 0; i < n; i++) {
        const float *qi = S->qkv[0] + (size_t)i * d + base;
        float maxs = -3.4e38f;
        for (int j = 0; j < n; j++) {
          const float *kj = S->qkv[1] + (size_t)j * d + base;
          float acc = 0.0f;
          for (int c = 0; c < SS_HEAD_DIM; c++) acc += qi[c] * kj[c];
          S->att[j] = acc * inv_sqrt;
          if (S->att[j] > maxs) maxs = S->att[j];
        }
        float z = 0.0f;
        for (int j = 0; j < n; j++) { S->att[j] = ss_expf(S->att[j] - maxs); z += S->att[j]; }
        for (int j = 0; j < n; j++) S->att[j] /= z;
        float *ctx = S->ctx + (size_t)i * d + base;
        for (int c = 0; c < SS_HEAD_DIM; c++) ctx[c] = 0.0f;
        for (int j = 0; j < n; j++) {
          const float *vj = S->qkv[2] + (size_t)j * d + base, a = S->att[j];
          for (int c = 0; c < SS_HEAD_DIM; c++) ctx[c] += a * vj[c];
        }
      }
    }
    quantize_rows(S->ctx, n, d, S->xq, S->xs);
    linear(S->xq, S->xs, n, d, d, SS_W + L->o_lv, (const uint16_t *)W_AT(L->o_sc), (const float *)W_AT(L->o_bi), S->h, S->wbuf, S->gsbuf);
    for (int t = 0; t < n; t++) for (int i = 0; i < d; i++) S->x[(size_t)t * d + i] += S->h[(size_t)t * d + i];
    layer_norm(S->x, n, d, (const float *)W_AT(L->ln1_w), (const float *)W_AT(L->ln1_b));

    quantize_rows(S->x, n, d, S->xq, S->xs);
    linear(S->xq, S->xs, n, d, SS_FFN, SS_W + L->up_lv, (const uint16_t *)W_AT(L->up_sc), (const float *)W_AT(L->up_bi), S->h, S->wbuf, S->gsbuf);
    for (size_t i = 0; i < (size_t)n * SS_FFN; i++) S->h[i] = ss_gelu(S->h[i]);
    quantize_rows(S->h, n, SS_FFN, S->xq, S->xs);
    linear(S->xq, S->xs, n, SS_FFN, d, SS_W + L->dn_lv, (const uint16_t *)W_AT(L->dn_sc), (const float *)W_AT(L->dn_bi), S->ctx, S->wbuf, S->gsbuf);
    for (int t = 0; t < n; t++) for (int i = 0; i < d; i++) S->x[(size_t)t * d + i] += S->ctx[(size_t)t * d + i];
    layer_norm(S->x, n, d, (const float *)W_AT(L->ln2_w), (const float *)W_AT(L->ln2_b));
  }

  /* Pointer logits for every token, once. The reference sums the log-partition terms as ((-Zunit - Z0) - Z1) - ...,
   * and float addition is not associative, so the same order is reproduced here. */
  float *plog = S->ctx;
  for (int t = 0; t < n; t++)
    row_linear(S->x + (size_t)t * d, d, SS_POINTERS, (const int8_t *)W_AT(SS_OFF_PTR_LEVELS),
               (const float *)W_AT(SS_OFF_PTR_SCALE), (const float *)W_AT(SS_OFF_PTR_BIAS), plog + (size_t)t * SS_POINTERS);
  float zp[SS_POINTERS];
  for (int r = 0; r < SS_POINTERS; r++) {
    int arg = 0;
    float maxv = plog[r];
    for (int t = 1; t < n; t++) { float v = plog[(size_t)t * SS_POINTERS + r]; if (v > maxv) { maxv = v; arg = t; } }
    float z = 0.0f;
    for (int t = 0; t < n; t++) z += ss_expf(plog[(size_t)t * SS_POINTERS + r] - maxv);
    out->ptr[r] = arg;
    zp[r] = ss_logf(z);
  }
  float unit[SS_UNITS];
  row_linear(S->x, d, SS_UNITS, (const int8_t *)W_AT(SS_OFF_UNIT_LEVELS), (const float *)W_AT(SS_OFF_UNIT_SCALE),
             (const float *)W_AT(SS_OFF_UNIT_BIAS), unit);
  int ua = 0;
  float um = unit[0];
  for (int i = 1; i < SS_UNITS; i++) if (unit[i] > um) { um = unit[i]; ua = i; }
  float zu = 0.0f;
  for (int i = 0; i < SS_UNITS; i++) zu += ss_expf(unit[i] - um);
  out->unit = ua;
  float score = -ss_logf(zu);
  for (int r = 0; r < SS_POINTERS; r++) score -= zp[r];
  out->score = score;
  row_linear(S->x, d, 1, (const int8_t *)W_AT(SS_OFF_DEFER_LEVELS), (const float *)W_AT(SS_OFF_DEFER_SCALE),
             (const float *)W_AT(SS_OFF_DEFER_BIAS), &out->defer_logit);
  return 0;
}
"""


LAYER_STRUCT = """
struct ss_layer {
  unsigned qkv_lv[3], qkv_sc[3], qkv_bi[3];
  unsigned o_lv, o_sc, o_bi, up_lv, up_sc, up_bi, dn_lv, dn_sc, dn_bi;
  unsigned ln1_w, ln1_b, ln2_w, ln2_b;
};
static const struct ss_layer SS_LAYER[SS_LAYERS] = {
{rows}
};
"""


def emit(p: Packed, out_dir: str | Path, section: str | None = None) -> dict:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    blob, off = build_blob(p)
    cfg = p.config
    d, heads = cfg["d_model"], cfg["heads"]
    head_dim, ffn = d // heads, cfg["ffn_mult"] * d
    inv = float(inv_sqrt_head_dim(head_dim))  # exactly the reference's expression: divide in double, round once.
    # Rounding the square root to float32 first and then dividing differs by one unit in the last place at
    # head_dim 24, which was enough to break bit-exactness for the XS student while leaving S unaffected.

    header = HEADER.format(layers=cfg["layers"], d=d, heads=heads, head_dim=head_dim, ffn=ffn, max_len=MAX_LEN,
                           bits=p.bits, group=GROUP, vocab=p.tok.levels.shape[0], pad=PAD, cls=CLS,
                           n_ptr=len(POINTERS), n_unit=len(UNIT_CLASSES), nbytes=len(blob.buf))
    defines = [f"#define SS_INV_SQRT_HEAD_DIM {inv:.9g}f"]
    for key in ("tok_levels", "tok_scale", "pos_levels", "pos_scale", "ln_in_w", "ln_in_b",
                "ptr_levels", "ptr_scale", "ptr_bias", "unit_levels", "unit_scale", "unit_bias",
                "defer_levels", "defer_scale", "defer_bias"):
        defines.append(f"#define SS_OFF_{key.upper()} {off[key]}u")
    rows = []
    for i in range(cfg["layers"]):
        g = lambda k: off[f"b{i}_{k}"]  # noqa: E731
        rows.append("  { {%s}, {%s}, {%s}, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d }," % (
            ", ".join(f"{g(f'{x}_lv')}u" for x in "qkv"), ", ".join(f"{g(f'{x}_sc')}u" for x in "qkv"),
            ", ".join(f"{g(f'{x}_bi')}u" for x in "qkv"),
            g("o_lv"), g("o_sc"), g("o_bi"), g("up_lv"), g("up_sc"), g("up_bi"), g("down_lv"), g("down_sc"), g("down_bi"),
            g("ln1_w"), g("ln1_b"), g("ln2_w"), g("ln2_b")))
    header = header.replace("extern const unsigned char SS_W",
                            "\n".join(defines) + "\n" + LAYER_STRUCT.replace("{rows}", "\n".join(rows)) + "\nextern const unsigned char SS_W")
    (out / "ss_kernel.h").write_text(header)

    attr = f'__attribute__((aligned(64), section("{section}")))' if section else "__attribute__((aligned(64)))"
    (out / "ss_weights.c").write_text(
        "/* Generated by static_student.codegen.emit. Do not edit. */\n#include \"ss_kernel.h\"\n\n"
        f"/* {len(blob.buf)} bytes: the whole model, as read-only program data. */\n"
        f"{attr}\nconst unsigned char SS_W[SS_WEIGHT_BYTES] = {{\n  " + _c_array(bytes(blob.buf)) + "\n};\n")
    (out / "ss_kernel.c").write_text(KERNEL)
    manifest = {**p.manifest(), "weight_bytes": len(blob.buf), "sections": [{"name": n, "offset": o, "bytes": ln} for n, o, ln in blob.names],
                "scratch_bytes": 4 * (MAX_LEN * d + MAX_LEN * ffn + 3 * MAX_LEN * d + MAX_LEN + MAX_LEN * d + MAX_LEN + ffn * d // GROUP) + MAX_LEN * ffn + ffn * d}
    (out / "manifest.json").write_text(__import__("json").dumps(manifest, indent=1) + "\n")
    return manifest
