"""Emit a native kernel for an imported ModernBERT classifier: weights as a linked constant, C that matches the reference.

Output directory contents:
  mb_weights.bin   every tensor the kernel reads, in the shipped precision, 64-byte aligned
  mb_weights.S     places mb_weights.bin in a read-only section under the symbol `mb_W` (assembler `.incbin`, so a
                   400 MB constant never passes through a C compiler as text)
  mb_model.h       dimensions, layer types, and the byte offset of every tensor inside mb_W
  mb_kernel.c      the forward pass (fixed source; only the header changes between models)
  mb_cli.c         line driver: token ids in, "<label> <prob> <logit...>" out, floats as exact hex
Every floating-point operation is performed in the order `modernbert.forward` performs it, so the outputs are
bit-identical to the reference on any IEEE-754 machine that honours -ffp-contract=off. Integer dot products may be
vectorized freely, because an exact integer sum does not depend on its order.
"""
from __future__ import annotations

import hashlib
import json
import platform
import subprocess
from pathlib import Path

import numpy as np

from static_student.codegen.modernbert import GROUP, MAX_TOKENS, MBPacked

ALIGN = 64


class Blob:
    def __init__(self):
        self.parts, self.size, self.off = [], 0, {}

    def add(self, name: str, a: np.ndarray) -> int:
        pad = (-self.size) % ALIGN
        if pad:
            self.parts.append(b"\0" * pad)
            self.size += pad
        b = np.ascontiguousarray(a).tobytes()
        self.off[name] = self.size
        self.parts.append(b)
        self.size += len(b)
        return self.off[name]


def _f32(a):
    return np.asarray(a, dtype=np.float32)


def pack_levels(levels: np.ndarray, bits: int) -> np.ndarray:
    """Row-major levels in the shipped width: one per byte at 8 bits, two per byte at 4 bits (low nibble first)."""
    if bits == 8:
        return levels.astype(np.int8)
    assert bits == 4 and levels.shape[-1] % 2 == 0 and levels.min() >= -8 and levels.max() <= 7
    nib = (levels.astype(np.int16) & 0xF).astype(np.uint8)
    return (nib[..., 0::2] | (nib[..., 1::2] << 4)).astype(np.uint8)


def build_blob(p: MBPacked) -> tuple[bytes, dict]:
    b = Blob()
    b.add("tok_levels", p.tok.levels.astype(np.int8))
    b.add("tok_scale", _f32(p.tok.scale))
    b.add("emb_norm", _f32(p.emb_norm))
    for i, L in enumerate(p.layers):
        if L["attn_norm"] is not None:
            b.add(f"l{i}_attn_norm", _f32(L["attn_norm"]))
        b.add(f"l{i}_mlp_norm", _f32(L["mlp_norm"]))
        for k in ("qkv", "o", "wi", "wo"):
            b.add(f"l{i}_{k}_levels", pack_levels(L[k].levels, p.bits))
            b.add(f"l{i}_{k}_scales", _f32(L[k].scales))
    b.add("final_norm", _f32(p.final_norm))
    b.add("head_levels", pack_levels(p.head_dense.levels, p.bits))
    b.add("head_scales", _f32(p.head_dense.scales))
    b.add("head_norm", _f32(p.head_norm))
    b.add("cls_levels", p.cls.levels.astype(np.int8))
    b.add("cls_scale", _f32(p.cls.scale))
    b.add("cls_bias", _f32(p.cls_bias))
    for t in ("full_attention", "sliding_attention"):
        cos, sin = p.rope[t]
        b.add(f"rope_{t}_cos", _f32(cos))
        b.add(f"rope_{t}_sin", _f32(sin))
    return b"".join(b.parts), b.off


def header(p: MBPacked, off: dict) -> str:
    c = p.config
    L = c["layers"]
    rows = []
    for i in range(L):
        an = off.get(f"l{i}_attn_norm", 0)
        rows.append("  {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d}" % (
            1 if c["layer_types"][i] == "sliding_attention" else 0, 1 if i > 0 else 0, an, off[f"l{i}_mlp_norm"],
            off[f"l{i}_qkv_levels"], off[f"l{i}_qkv_scales"], off[f"l{i}_o_levels"], off[f"l{i}_o_scales"],
            off[f"l{i}_wi_levels"], off[f"l{i}_wi_scales"], off[f"l{i}_wo_levels"], off[f"l{i}_wo_scales"]))
    return f"""/* GENERATED by static_student/codegen/emit_modernbert.py. Do not edit. */
#ifndef MB_MODEL_H
#define MB_MODEL_H
#include <stddef.h>
#include <stdint.h>
#define MB_D {c['hidden']}
#define MB_HEADS {c['heads']}
#define MB_HD {c['head_dim']}
#define MB_INTER {c['inter']}
#define MB_LAYERS {L}
#define MB_WINDOW {c['window']}
#define MB_LABELS {c['labels']}
#define MB_VOCAB {c['vocab']}
#define MB_GROUP {GROUP}
#define MB_BITS {p.bits}
#define MB_MAX_T {MAX_TOKENS}
#define MB_EPS {np.float32(c['eps']).item().hex()}f
#define MB_SCALE_QK {np.float32(c['head_dim'] ** -0.5).item().hex()}f
#define MB_OFF_TOK_LEVELS {off['tok_levels']}
#define MB_OFF_TOK_SCALE {off['tok_scale']}
#define MB_OFF_EMB_NORM {off['emb_norm']}
#define MB_OFF_FINAL_NORM {off['final_norm']}
#define MB_OFF_HEAD_LEVELS {off['head_levels']}
#define MB_OFF_HEAD_SCALES {off['head_scales']}
#define MB_OFF_HEAD_NORM {off['head_norm']}
#define MB_OFF_CLS_LEVELS {off['cls_levels']}
#define MB_OFF_CLS_SCALE {off['cls_scale']}
#define MB_OFF_CLS_BIAS {off['cls_bias']}
#define MB_OFF_ROPE_FULL_COS {off['rope_full_attention_cos']}
#define MB_OFF_ROPE_FULL_SIN {off['rope_full_attention_sin']}
#define MB_OFF_ROPE_SLIDE_COS {off['rope_sliding_attention_cos']}
#define MB_OFF_ROPE_SLIDE_SIN {off['rope_sliding_attention_sin']}
struct mb_layer {{ int sliding, has_attn_norm; size_t attn_norm, mlp_norm, qkv_l, qkv_s, o_l, o_s, wi_l, wi_s, wo_l, wo_s; }};
static const struct mb_layer MB_LAYER[MB_LAYERS] = {{
{",".join(chr(10) + r for r in rows)[1:]}
}};
extern const unsigned char mb_W[];
int mb_forward(const int32_t *ids, int n, float *logits, int *label, float *prob);
#endif
"""


ASM = r"""/* GENERATED: the weights as a linker-visible read-only constant. */
#if defined(__APPLE__)
  .section __TEXT,__const
  .globl _mb_W
  .p2align 6
_mb_W:
  .incbin "mb_weights.bin"
#else
  .section .rodata
  .globl mb_W
  .p2align 6
mb_W:
  .incbin "mb_weights.bin"
  .section .note.GNU-stack,"",@progbits
#endif
"""

KERNEL = r"""/* Forward pass of an imported ModernBERT classifier. Fixed source: dimensions and offsets come from mb_model.h.
 * Float operations mirror static_student/codegen/modernbert.py one for one; integer dot products are exact. */
#include "mb_model.h"
#include <math.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>

#if defined(__ARM_FEATURE_DOTPROD) && MB_GROUP == 32 && !defined(MB_PORTABLE)
#include <arm_neon.h>
#define MB_SDOT 1
#else
#define MB_SDOT 0
#endif

#define W(off) ((const void *)(mb_W + (off)))
static const float MAGIC = 12582912.0f;
static inline float rne(float x) { return (x + MAGIC) - MAGIC; }

static float mb_expf(float x) {
  const float LOG2E = 1.4426950408889634f, LN2_HI = 0.693145751953125f, LN2_LO = 1.428606765330187e-06f;
  if (x < -87.0f) return 0.0f;
  float k = rne(x * LOG2E);
  float r = (x - k * LN2_HI) - k * LN2_LO;
  float p = 0.0013888889f;
  p = p * r + 0.008333334f; p = p * r + 0.041666668f; p = p * r + 0.16666667f;
  p = p * r + 0.5f;         p = p * r + 1.0f;         p = p * r + 1.0f;
  int ki = (int)k; if (ki < -126) ki = -126; if (ki > 127) ki = 127;
  union { uint32_t u; float f; } two_k; two_k.u = (uint32_t)(ki + 127) << 23;
  return p * two_k.f;
}

static float mb_erff(float x) {
  const float P = 0.3275911f;
  float s = x < 0.0f ? -1.0f : 1.0f, a = x < 0.0f ? -x : x;
  float t = 1.0f / (1.0f + P * a);
  float p = 1.061405429f;
  p = p * t + -1.453152027f; p = p * t + 1.421413741f; p = p * t + -0.284496736f; p = p * t + 0.254829592f;
  return s * (1.0f - p * t * mb_expf(-(a * a)));
}

static inline float mb_gelu(float x) { return 0.5f * x * (1.0f + mb_erff(x * 0.70710678118654752f)); }

/* bias-free LayerNorm; the reference adds a zero bias, so we do too (x + 0.0f can change the sign of a zero) */
static void norm(float *x, int n, int d, const float *w) {
  for (int t = 0; t < n; t++) {
    float *row = x + (size_t)t * d, sum = 0.0f;
    for (int i = 0; i < d; i++) sum += row[i];
    float mean = sum / (float)d, var = 0.0f;
    for (int i = 0; i < d; i++) { float dx = row[i] - mean; var += dx * dx; }
    float inv = 1.0f / sqrtf(var / (float)d + MB_EPS);
    for (int i = 0; i < d; i++) row[i] = (row[i] - mean) * inv * w[i] + 0.0f;
  }
}

static void quantize_rows(const float *x, int n, int d, int8_t *q, float *scale) {
  for (int t = 0; t < n; t++) {
    const float *row = x + (size_t)t * d;
    float amax = 0.0f;
    for (int i = 0; i < d; i++) { float a = row[i] < 0.0f ? -row[i] : row[i]; if (a > amax) amax = a; }
    float s = (amax < 1e-8f ? 1e-8f : amax) / 127.0f;
    scale[t] = s;
    for (int i = 0; i < d; i++) {
      float v = rne(row[i] / s);
      q[(size_t)t * d + i] = (int8_t)(v < -127.0f ? -127.0f : (v > 127.0f ? 127.0f : v));
    }
  }
}

static inline int32_t dot_group(const int8_t *a, const int8_t *b) {
  int32_t s = 0;
  for (int i = 0; i < MB_GROUP; i++) s += (int32_t)a[i] * (int32_t)b[i];
  return s;
}

/* one weight row in the shipped width -> int8 levels */
static inline void unpack_row(const unsigned char *src, int in, int8_t *dst) {
#if MB_BITS == 8
  memcpy(dst, src, (size_t)in);
#else
  for (int i = 0; i < in / 2; i++) {
    int lo = src[i] & 0xF, hi = src[i] >> 4;
    dst[2 * i] = (int8_t)(lo >= 8 ? lo - 16 : lo);
    dst[2 * i + 1] = (int8_t)(hi >= 8 ? hi - 16 : hi);
  }
#endif
}

static int mb_threads(void) {
  static int T = 0;
  if (!T) { const char *e = getenv("MB_THREADS"); T = e ? atoi(e) : 1; if (T < 1) T = 1; if (T > 64) T = 64; }
  return T;
}

/* Run fn over items [0, n) split into contiguous ranges, one per thread. Every item is computed by exactly one thread
 * with the same instruction sequence, so results do not depend on the thread count. */
typedef void (*range_fn)(const void *ctx, int a, int b);
struct par_job { range_fn fn; const void *ctx; int a, b; };
static void *par_run(void *p) { const struct par_job *j = (const struct par_job *)p; j->fn(j->ctx, j->a, j->b); return NULL; }

static void par_for(int n, range_fn fn, const void *ctx) {
  int T = mb_threads();
  if (T > n) T = n;
  if (T <= 1) { fn(ctx, 0, n); return; }
  struct par_job J[64];
  pthread_t th[64];
  for (int i = 0; i < T; i++) {
    J[i] = (struct par_job){fn, ctx, (int)((long)n * i / T), (int)((long)n * (i + 1) / T)};
    if (i) pthread_create(&th[i], NULL, par_run, &J[i]);
  }
  par_run(&J[0]);
  for (int i = 1; i < T; i++) pthread_join(th[i], NULL);
}

struct lin_job { const int8_t *xq; const float *xs; int n, in, out; const unsigned char *lv; const float *gs; float *y; };

/* one weight row as int8 levels: in place at 8 bits, unpacked into buf at 4 bits */
static inline const int8_t *row_levels(const struct lin_job *J, int o, int8_t *buf) {
  const size_t row_bytes = (size_t)J->in * MB_BITS / 8;
#if MB_BITS == 8
  (void)buf;
  return (const int8_t *)(J->lv + (size_t)o * row_bytes);
#else
  unpack_row(J->lv + (size_t)o * row_bytes, J->in, buf);
  return buf;
#endif
}

/* y[t, o] = (sum_g gscale[o, g] * <W[o, g], xq[t, g]>) * xscale[t]. Every output has its own float accumulator and adds
 * its groups in order g = 0, 1, ...; the loops below only decide how many outputs advance together. */
static void linear_one(const struct lin_job *J, int o, const int8_t *w) {
  const int groups = J->in / MB_GROUP;
  const float *g = J->gs + (size_t)o * groups;
  const size_t in = (size_t)J->in;
  int t = 0;
  for (; t + 4 <= J->n; t += 4) {  /* four independent accumulators, one per token */
    const int8_t *x0 = J->xq + (size_t)t * in, *x1 = x0 + in, *x2 = x1 + in, *x3 = x2 + in;
    float a0 = 0.0f, a1 = 0.0f, a2 = 0.0f, a3 = 0.0f;
    for (int k = 0; k < groups; k++) {
      const int8_t *wk = w + (size_t)k * MB_GROUP;
      const size_t c = (size_t)k * MB_GROUP;
      a0 += (float)dot_group(wk, x0 + c) * g[k];
      a1 += (float)dot_group(wk, x1 + c) * g[k];
      a2 += (float)dot_group(wk, x2 + c) * g[k];
      a3 += (float)dot_group(wk, x3 + c) * g[k];
    }
    J->y[(size_t)t * J->out + o] = a0 * J->xs[t];
    J->y[(size_t)(t + 1) * J->out + o] = a1 * J->xs[t + 1];
    J->y[(size_t)(t + 2) * J->out + o] = a2 * J->xs[t + 2];
    J->y[(size_t)(t + 3) * J->out + o] = a3 * J->xs[t + 3];
  }
  for (; t < J->n; t++) {
    const int8_t *xr = J->xq + (size_t)t * J->in;
    float acc = 0.0f;
    for (int k = 0; k < groups; k++) acc += (float)dot_group(w + (size_t)k * MB_GROUP, xr + (size_t)k * MB_GROUP) * g[k];
    J->y[(size_t)t * J->out + o] = acc * J->xs[t];
  }
}

#if MB_SDOT
/* exact int32 sums of one 32-wide group of w against four token rows (x vectors preloaded), one lane per token */
static inline int32x4_t sums4(int8x16_t w0, int8x16_t w1, const int8x16_t *xv) {
  const int32x4_t z = vdupq_n_s32(0);
  int32x4_t d0 = vdotq_s32(vdotq_s32(z, w0, xv[0]), w1, xv[1]);
  int32x4_t d1 = vdotq_s32(vdotq_s32(z, w0, xv[2]), w1, xv[3]);
  int32x4_t d2 = vdotq_s32(vdotq_s32(z, w0, xv[4]), w1, xv[5]);
  int32x4_t d3 = vdotq_s32(vdotq_s32(z, w0, xv[6]), w1, xv[7]);
  return vpaddq_s32(vpaddq_s32(d0, d1), vpaddq_s32(d2, d3));
}

/* four output rows x four tokens per step: each loaded token vector serves four rows. Lanes past n read spare rows
 * of XQ and are dropped. */
static void linear_tile4(const struct lin_job *J, int o, const int8_t *const w[4]) {
  const int groups = J->in / MB_GROUP, n = J->n;
  const size_t in = (size_t)J->in;
  const float *g[4];
  for (int r = 0; r < 4; r++) g[r] = J->gs + (size_t)(o + r) * groups;
  for (int t = 0; t < n; t += 4) {
    const int8_t *x = J->xq + (size_t)t * in;
    float32x4_t acc[4] = {vdupq_n_f32(0.0f), vdupq_n_f32(0.0f), vdupq_n_f32(0.0f), vdupq_n_f32(0.0f)};
    for (int k = 0; k < groups; k++) {
      const size_t c = (size_t)k * MB_GROUP;
      int8x16_t xv[8];
      for (int i = 0; i < 4; i++) { xv[2 * i] = vld1q_s8(x + i * in + c); xv[2 * i + 1] = vld1q_s8(x + i * in + c + 16); }
      for (int r = 0; r < 4; r++) {
        const int32x4_t s = sums4(vld1q_s8(w[r] + c), vld1q_s8(w[r] + c + 16), xv);
        acc[r] = vaddq_f32(acc[r], vmulq_f32(vcvtq_f32_s32(s), vdupq_n_f32(g[r][k])));
      }
    }
    for (int r = 0; r < 4; r++) {
      float a[4];
      vst1q_f32(a, acc[r]);
      for (int i = 0; i < 4 && t + i < n; i++) J->y[(size_t)(t + i) * J->out + o + r] = a[i] * J->xs[t + i];
    }
  }
}
#endif

static void linear_rows(const void *arg, int o0, int o1) {
  const struct lin_job *J = (const struct lin_job *)arg;
  static _Thread_local int8_t buf[4][2 * MB_INTER > MB_D ? 2 * MB_INTER : MB_D];
  int o = o0;
#if MB_SDOT
  for (; o + 4 <= o1; o += 4) {
    const int8_t *w[4];
    for (int r = 0; r < 4; r++) w[r] = row_levels(J, o + r, buf[r]);
    linear_tile4(J, o, w);
  }
#endif
  for (; o < o1; o++) linear_one(J, o, row_levels(J, o, buf[0]));
}

static void linear(const int8_t *xq, const float *xs, int n, int in, int out, const unsigned char *lv, const float *gs, float *y) {
  const struct lin_job J = {xq, xs, n, in, out, lv, gs, y};
  par_for(out, linear_rows, &J);
}

static float X[MB_MAX_T * MB_D], H[MB_MAX_T * MB_D], QKV[MB_MAX_T * 3 * MB_D], CTX[MB_MAX_T * MB_D];
static float U[MB_MAX_T * 2 * MB_INTER], G[MB_MAX_T * MB_INTER], Y[MB_MAX_T * MB_D];
static int8_t XQ[(MB_MAX_T + 4) * 2 * MB_INTER];
static float XS[MB_MAX_T];

static void lin(const float *x, int n, int in, int out, size_t lv, size_t gs, float *y) {
  quantize_rows(x, n, in, XQ, XS);
  linear(XQ, XS, n, in, out, (const unsigned char *)W(lv), (const float *)W(gs), y);
}

static void rotate(float *v, int t, const float *cos, const float *sin) {
  float tmp[MB_HD];
  const int h = MB_HD / 2;
  for (int i = 0; i < MB_HD; i++) {
    float rot = i < h ? -v[i + h] : v[i - h];
    tmp[i] = v[i] * cos[(size_t)t * MB_HD + i] + rot * sin[(size_t)t * MB_HD + i];
  }
  memcpy(v, tmp, sizeof tmp);
}

struct attn_job { int n, sliding; };

/* One head per item. Scores for four keys are carried at once and the context accumulates all MB_HD lanes per key;
 * every score and every context element still sums its terms in the reference order. */
static void attn_heads(const void *arg, int h0, int h1) {
  const struct attn_job *A = (const struct attn_job *)arg;
  const int n = A->n, d = MB_D;
  float att[MB_MAX_T], acc[MB_HD];
  for (int hh = h0; hh < h1; hh++)
    for (int i = 0; i < n; i++) {
      const float *q = QKV + (size_t)i * 3 * d + (size_t)hh * MB_HD;
      const float *kb = QKV + d + (size_t)hh * MB_HD, *vb = QKV + 2 * d + (size_t)hh * MB_HD;
      int j = 0;
      for (; j + 4 <= n; j += 4) {
        const float *k0 = kb + (size_t)j * 3 * d, *k1 = k0 + 3 * d, *k2 = k1 + 3 * d, *k3 = k2 + 3 * d;
        float s0 = 0.0f, s1 = 0.0f, s2 = 0.0f, s3 = 0.0f;
        for (int e = 0; e < MB_HD; e++) { s0 += q[e] * k0[e]; s1 += q[e] * k1[e]; s2 += q[e] * k2[e]; s3 += q[e] * k3[e]; }
        att[j] = s0; att[j + 1] = s1; att[j + 2] = s2; att[j + 3] = s3;
      }
      for (; j < n; j++) {
        const float *k = kb + (size_t)j * 3 * d;
        float s = 0.0f;
        for (int e = 0; e < MB_HD; e++) s += q[e] * k[e];
        att[j] = s;
      }
      float m = -INFINITY;
      for (j = 0; j < n; j++) {
        float s = att[j] * MB_SCALE_QK;
        if (A->sliding) s = s + ((i - j > MB_WINDOW || j - i > MB_WINDOW) ? -1e4f : 0.0f);
        att[j] = s;
        if (s > m) m = s;
      }
      float z = 0.0f;
      for (j = 0; j < n; j++) { att[j] = mb_expf(att[j] - m); z += att[j]; }
      for (j = 0; j < n; j++) att[j] = att[j] / z;
      for (int e = 0; e < MB_HD; e++) acc[e] = 0.0f;
      for (j = 0; j < n; j++) {
        const float a = att[j], *v = vb + (size_t)j * 3 * d;
        for (int e = 0; e < MB_HD; e++) acc[e] += a * v[e];
      }
      memcpy(CTX + (size_t)i * d + (size_t)hh * MB_HD, acc, sizeof acc);
    }
}

/* GLU with erf-GELU, one token per item */
static void glu_tokens(const void *arg, int t0, int t1) {
  (void)arg;
  for (int t = t0; t < t1; t++)
    for (int i = 0; i < MB_INTER; i++)
      G[(size_t)t * MB_INTER + i] = mb_gelu(U[(size_t)t * 2 * MB_INTER + i]) * U[(size_t)t * 2 * MB_INTER + MB_INTER + i];
}

int mb_forward(const int32_t *ids, int n, float *logits, int *label, float *prob) {
  if (n <= 0 || n > MB_MAX_T) return -1;
  const int d = MB_D;
  const int8_t *tl = (const int8_t *)W(MB_OFF_TOK_LEVELS);
  const float *ts = (const float *)W(MB_OFF_TOK_SCALE);
  for (int t = 0; t < n; t++) {
    if (ids[t] < 0 || ids[t] >= MB_VOCAB) return -1;
    for (int i = 0; i < d; i++) X[(size_t)t * d + i] = (float)tl[(size_t)ids[t] * d + i] * ts[ids[t]];
  }
  norm(X, n, d, (const float *)W(MB_OFF_EMB_NORM));
  for (int l = 0; l < MB_LAYERS; l++) {
    const struct mb_layer *L = &MB_LAYER[l];
    memcpy(H, X, sizeof(float) * (size_t)n * d);
    if (L->has_attn_norm) norm(H, n, d, (const float *)W(L->attn_norm));
    lin(H, n, d, 3 * d, L->qkv_l, L->qkv_s, QKV);
    const float *cos = (const float *)W(L->sliding ? MB_OFF_ROPE_SLIDE_COS : MB_OFF_ROPE_FULL_COS);
    const float *sin = (const float *)W(L->sliding ? MB_OFF_ROPE_SLIDE_SIN : MB_OFF_ROPE_FULL_SIN);
    for (int t = 0; t < n; t++)
      for (int hh = 0; hh < MB_HEADS; hh++) {
        rotate(QKV + (size_t)t * 3 * d + (size_t)hh * MB_HD, t, cos, sin);          /* q */
        rotate(QKV + (size_t)t * 3 * d + d + (size_t)hh * MB_HD, t, cos, sin);      /* k */
      }
    const struct attn_job A = {n, L->sliding};
    par_for(MB_HEADS, attn_heads, &A);
    lin(CTX, n, d, d, L->o_l, L->o_s, Y);
    for (size_t i = 0; i < (size_t)n * d; i++) X[i] = X[i] + Y[i];
    memcpy(H, X, sizeof(float) * (size_t)n * d);
    norm(H, n, d, (const float *)W(L->mlp_norm));
    lin(H, n, d, 2 * MB_INTER, L->wi_l, L->wi_s, U);
    par_for(n, glu_tokens, NULL);
    lin(G, n, MB_INTER, d, L->wo_l, L->wo_s, Y);
    for (size_t i = 0; i < (size_t)n * d; i++) X[i] = X[i] + Y[i];
  }
  norm(X, n, d, (const float *)W(MB_OFF_FINAL_NORM));
  float pooled[MB_D], hid[MB_D];
  for (int i = 0; i < d; i++) {
    float s = 0.0f;
    for (int t = 0; t < n; t++) s += X[(size_t)t * d + i];
    pooled[i] = s / (float)n;
  }
  lin(pooled, 1, d, d, MB_OFF_HEAD_LEVELS, MB_OFF_HEAD_SCALES, hid);
  for (int i = 0; i < d; i++) hid[i] = mb_gelu(hid[i]);
  norm(hid, 1, d, (const float *)W(MB_OFF_HEAD_NORM));
  const int8_t *cl = (const int8_t *)W(MB_OFF_CLS_LEVELS);
  const float *cs = (const float *)W(MB_OFF_CLS_SCALE), *cb = (const float *)W(MB_OFF_CLS_BIAS);
  int best = 0;
  for (int o = 0; o < MB_LABELS; o++) {
    float acc = 0.0f, s = cs[o];
    for (int i = 0; i < d; i++) acc += hid[i] * ((float)cl[(size_t)o * d + i] * s);
    logits[o] = acc + cb[o];
    if (logits[o] > logits[best]) best = o;
  }
  float mx = logits[best], z = 0.0f;
  for (int o = 0; o < MB_LABELS; o++) z += mb_expf(logits[o] - mx);
  *label = best;
  *prob = 1.0f / z;
  return 0;
}
"""

CLI = r"""/* Token ids (space separated) per input line -> "<label> <prob> <logit_0> ... <logit_k>", floats in exact hex. */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include "mb_model.h"

int main(void) {
  char *line = NULL;
  size_t cap = 0;
  int32_t ids[MB_MAX_T];
  float logits[MB_LABELS], prob;
  int label;
  while (getline(&line, &cap, stdin) > 0) {
    int n = 0;
    char *p = line, *end;
    for (;;) {
      long v = strtol(p, &end, 10);
      if (end == p) break;
      if (n < MB_MAX_T) ids[n++] = (int32_t)v;
      p = end;
    }
    if (mb_forward(ids, n, logits, &label, &prob) != 0) { printf("ERR\n"); continue; }
    printf("%d %a", label, (double)prob);
    for (int o = 0; o < MB_LABELS; o++) printf(" %a", (double)logits[o]);
    printf("\n");
  }
  free(line);
  return 0;
}
"""


def cflags() -> list[str]:
    arch = ["-march=armv8.2-a+dotprod"] if platform.machine() in ("arm64", "aarch64") else ["-march=native"]
    return ["-O3", "-std=c11", "-ffp-contract=off", *arch]


def emit(p: MBPacked, out: str | Path) -> dict:
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    blob, off = build_blob(p)
    (out / "mb_weights.bin").write_bytes(blob)
    (out / "mb_weights.S").write_text(ASM)
    (out / "mb_model.h").write_text(header(p, off))
    (out / "mb_kernel.c").write_text(KERNEL)
    (out / "mb_cli.c").write_text(CLI)
    man = {"bits": p.bits, "config": p.config, "weight_bytes": len(blob), "weights_sha256": hashlib.sha256(blob).hexdigest(),
           "kernel_sha256": hashlib.sha256(KERNEL.encode()).hexdigest()}
    (out / "manifest.json").write_text(json.dumps(man, indent=1) + "\n")
    return man


def compile_cli(out: str | Path) -> Path:
    out = Path(out)
    f = cflags()
    subprocess.run(["cc", *f, "-c", "mb_weights.S", "-o", "mb_weights.o"], cwd=out, check=True)
    subprocess.run(["cc", *f, "-c", "mb_kernel.c", "-o", "mb_kernel.o"], cwd=out, check=True)
    subprocess.run(["cc", *f, "mb_cli.c", "mb_kernel.o", "mb_weights.o", "-o", "mb_cli", "-lm", "-lpthread"], cwd=out, check=True)
    return out / "mb_cli"


def run_cli(exe: Path, ids: list[np.ndarray], jobs: int = 12, threads: int = 1) -> list[str]:
    """Shard inputs across processes (one sequence at a time in each), return output lines in input order."""
    lines = [" ".join(str(int(v)) for v in x) for x in ids]
    k = max(1, min(jobs, len(lines)))
    bounds = [round(i * len(lines) / k) for i in range(k + 1)]
    procs = []
    for a, b in zip(bounds, bounds[1:]):
        pr = subprocess.Popen([str(exe)], stdin=subprocess.PIPE, stdout=subprocess.PIPE, env={**__import__("os").environ, "MB_THREADS": str(threads)})
        pr.stdin.write(("\n".join(lines[a:b]) + "\n").encode())
        pr.stdin.close()
        procs.append(pr)
    out = []
    for pr in procs:
        out.extend(pr.stdout.read().decode().splitlines())
        assert pr.wait() == 0
    assert len(out) == len(lines)
    return out
