"""The compiler: one spec line and a trained student in, one certified binary out, or no binary at all.

    python -m static_student.build --spec specs/telemetry.spec --model models/tel-mlx-S-w4 --out build/tel_S_w4

Stages, in order, because each one depends on the bytes the previous one produced:
  1. pack the student and emit `SS_W[]`, the kernel and the header;
  2. compile the kernel and run the calibration pool **through the compiled kernel**, so the scores that are certified
     are the scores that ship (the reference is bit-identical, but it is not what runs);
  3. Learn-then-Test on those scores. If no threshold satisfies the contract at the spec's minimum coverage, the build
     stops here and no binary is produced: that is the failing build, not an error to be worked around;
  4. emit the certificate record, then link kernel, weights, certificate, struct conversion and the *unchanged* legacy
     parser object into one executable;
  5. re-run a sample through the linked binary and check that it reproduces the kernel's own decisions.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

from static_student import certify
from static_student.codegen import emit, pack, run_kernel
from static_student.curriculum.spec import parse_spec
from static_student.student import data
from static_student.student.qat import load_student

REPO = Path(__file__).resolve().parent.parent
CFLAGS = ["-O3", "-std=c11", "-ffp-contract=off", "-Wall", "-Wextra"]


class BuildFailed(RuntimeError):
    pass


def _run(cmd: list[str]) -> None:
    r = subprocess.run(cmd, capture_output=True)
    if r.returncode != 0:
        raise BuildFailed(f"{' '.join(cmd[:3])}...: {r.stderr.decode(errors='replace')[:2000]}")


def compile_kernel(gen: Path, csrc: Path) -> Path:
    for src in ("ss_weights.c", "ss_kernel.c"):
        _run(["cc", *CFLAGS, "-I", str(gen), "-c", str(gen / src), "-o", str(gen / src.replace(".c", ".o"))])
    _run(["cc", *CFLAGS, "-I", str(gen), "-I", str(csrc), "-c", str(csrc / "ss_struct.c"), "-o", str(gen / "ss_struct.o")])
    exe = gen / "ss_cli"
    _run(["cc", *CFLAGS, "-I", str(gen), str(csrc / "ss_cli.c"), str(gen / "ss_kernel.o"), str(gen / "ss_weights.o"), "-o", str(exe), "-lm"])
    return exe


def kernel_scores(exe: Path, payloads: list[bytes], jobs: int | None = None) -> dict[str, np.ndarray]:
    return run_kernel.score(exe, payloads, jobs)


def outcomes(rows, k) -> tuple[np.ndarray, np.ndarray]:
    """wrong[i] = accepting payload i would violate the contract; emits[i] = its spans decode to a struct."""
    got = [data.decode(r.payload, k["ptr"][i], int(k["unit"][i])) for i, r in enumerate(rows)]
    emits = np.array([g is not None for g in got])
    wrong = np.array([int(g is None or r.defer or g != (r.latency_us, r.user_id)) for r, g in zip(rows, got)])
    return wrong, emits


def emit_certificate(cert: certify.Certificate, weights_sha: str, path: Path) -> None:
    f = lambda x: f"{float(x):.9g}f"  # noqa: E731
    path.write_text(
        '/* Generated by static_student.build. The contract this binary was certified against. */\n'
        '#include "ss_hybrid.h"\n\n'
        '__attribute__((used))\nconst ss_certificate SS_CERTIFICATE = {\n'
        f'  .magic = "SSCERT01",\n  .alpha = {f(cert.alpha)}, .delta = {f(cert.delta)},\n'
        f'  .tau = {f(cert.tau)}, .coverage = {f(cert.coverage)},\n  .n = {cert.n_accepted}u, .k = {cert.k_wrong}u,\n'
        f'  .weights_sha256 = "{weights_sha}",\n  .pool_sha256 = "{cert.pool_sha256}",\n  .grid_sha256 = "{cert.grid_sha256}",\n}};\n')


def main(argv=None) -> dict:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--spec", required=True)
    ap.add_argument("--model", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--cal", type=int, default=20_000, help="calibration payloads drawn from families the student never trained on")
    ap.add_argument("--jobs", type=int, default=None, help="parallel kernel shards (default: most of the cores)")
    ap.add_argument("--section", default=None, help="put SS_W[] in this section, e.g. __DATA,__ss_weights")
    args = ap.parse_args(argv)

    t0 = time.time()
    spec = parse_spec(REPO / args.spec)
    mdir = REPO / args.model
    out = REPO / args.out
    out.mkdir(parents=True, exist_ok=True)
    rep = json.loads((mdir / "train_report.json").read_text())
    model, _ = load_student(mdir)
    model.eval()

    packed = pack.pack(model)
    man = emit.emit(packed, out, section=args.section)
    print(f"[build] emitted {man['weight_bytes']:,} bytes of weights ({time.time() - t0:.0f}s)", flush=True)
    exe = compile_kernel(out, REPO / "csrc")

    split = data.split_families(data.load_families(REPO / rep["families_path"]), seed=rep["seed"])
    dev_rows = data.render_rows(split["dev"], args.cal, "cert-dev")
    cal_rows = data.render_rows(split["defer_fit"], args.cal, "cert-cal")
    kd = kernel_scores(exe, [r.payload for r in dev_rows], args.jobs)
    kc = kernel_scores(exe, [r.payload for r in cal_rows], args.jobs)
    print(f"[build] scored {2 * args.cal:,} payloads through the compiled kernel ({time.time() - t0:.0f}s)", flush=True)
    _, dev_emits = outcomes(dev_rows, kd)
    wrong, emits = outcomes(cal_rows, kc)
    grid = certify.coverage_grid(kd["score"], dev_emits)
    pool_sha = hashlib.sha256(b"".join(r.payload for r in cal_rows)).hexdigest()

    try:
        cert = certify.certify(kc["score"], wrong, emits, spec["alpha"], spec["delta"], spec["min_coverage"], grid, pool_sha256=pool_sha)
    except certify.CertificationError as e:
        (out / "FAILED.txt").write_text(f"{e}\n")
        for stale in ("ss_hybrid", "ss_certificate.c"):
            (out / stale).unlink(missing_ok=True)
        raise BuildFailed(f"contract not met, no binary produced: {e}") from e

    emit_certificate(cert, packed.sha256(), out / "ss_certificate.c")
    csrc = REPO / "csrc"
    _run(["make", "-C", str(csrc)])
    objs = []
    for src in (out / "ss_certificate.c", csrc / "ss_hybrid.c"):
        o = out / (src.stem + ".o")
        _run(["cc", *CFLAGS, "-I", str(out), "-I", str(csrc), "-c", str(src), "-o", str(o)])
        objs.append(str(o))
    binary = out / "ss_hybrid"
    _run(["cc", *CFLAGS, "-I", str(out), "-I", str(csrc), str(csrc / "ss_hybrid_cli.c"), *objs,
          str(out / "ss_kernel.o"), str(out / "ss_weights.o"), str(out / "ss_struct.o"),
          str(REPO / "build/legacy_telemetry.o"), "-o", str(binary), "-lm", "-lstdc++",
          *subprocess.run(["pkg-config", "--libs", "re2"], capture_output=True, text=True).stdout.split()])

    check = subprocess.run([str(binary), "--certificate"], capture_output=True, check=True).stdout.decode("utf-8", "replace").strip()
    if cert.pool_sha256 not in check or packed.sha256() not in check:
        raise BuildFailed("the certificate in the binary does not name the weights and pool it was computed on")
    report = {"spec": args.spec, "spec_sha256": spec["sha256"], "model": args.model, "bits": rep.get("bits"), "size": rep.get("size"),
              "weights_sha256": packed.sha256(), "weight_bytes": man["weight_bytes"], "certificate": cert.as_dict(),
              "binary_bytes": binary.stat().st_size, "stripped_bytes": None, "seconds": round(time.time() - t0, 1),
              "certificate_line": check}
    stripped = out / "ss_hybrid.stripped"
    shutil.copy(binary, stripped)
    subprocess.run(["strip", "-x", str(stripped)], capture_output=True)
    report["stripped_bytes"] = stripped.stat().st_size
    (out / "build_report.json").write_text(json.dumps(report, indent=1, default=float) + "\n")
    print(json.dumps({k: report[k] for k in ("weight_bytes", "binary_bytes", "stripped_bytes", "seconds")}, indent=1))
    print("[build] certificate:", check[:150])
    return report


if __name__ == "__main__":
    try:
        main()
    except BuildFailed as e:
        print(f"[build] FAILED: {e}", file=sys.stderr)
        sys.exit(2)
